-- সম্মিলিত প্রয়াস Version 6.5.2 migration
-- Run ONCE in Supabase SQL Editor after the existing V6.4 migration.
-- Existing tables/data are preserved. This migration adds private fund-summary data.

create table if not exists public.fund_settings (
    id integer primary key default 1 check (id = 1),
    bank_balance numeric not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.fdr_investments (
    id bigint generated by default as identity primary key,
    name text not null,
    bank text not null,
    amount numeric not null default 0,
    maturity_date date,
    notes text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.dps_accounts (
    id bigint generated by default as identity primary key,
    name text not null,
    bank text not null,
    monthly_installment numeric not null default 0,
    start_date date,
    maturity_date date,
    notes text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.fund_settings enable row level security;
alter table public.fdr_investments enable row level security;
alter table public.dps_accounts enable row level security;

-- Flask uses the Supabase service-role key, so no anon read/write policies are required.
insert into public.fund_settings (id, bank_balance)
values (1, 0)
on conflict (id) do nothing;

create index if not exists fdr_investments_active_maturity_idx
    on public.fdr_investments (active, maturity_date);

create index if not exists dps_accounts_active_maturity_idx
    on public.dps_accounts (active, maturity_date);


-- v6.5.2.1 financial dashboard extension
-- Run this after the original v6.5.2 migration.
create table if not exists public.investment_settings (
    id integer primary key default 1 check (id = 1),
    land_purchase_amount numeric not null default 0,
    statement_balance numeric not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.dps_payments (
    id bigint generated by default as identity primary key,
    dps_id bigint not null references public.dps_accounts(id) on delete cascade,
    year integer not null,
    month integer not null check (month between 1 and 12),
    created_at timestamptz not null default now(),
    unique (dps_id, year, month)
);

alter table public.investment_settings enable row level security;
alter table public.dps_payments enable row level security;

insert into public.investment_settings (id, land_purchase_amount, statement_balance)
values (1, 0, 0)
on conflict (id) do nothing;

create index if not exists dps_payments_year_month_idx
    on public.dps_payments (year, month);
create index if not exists dps_payments_dps_year_idx
    on public.dps_payments (dps_id, year);
