-- সম্মিলিত প্রয়াস Version 6.6.0 migration
-- Run ONCE in Supabase SQL Editor after the existing 6.5.8 migration.
-- Existing data is preserved.

create table if not exists public.committee (
    id bigint generated by default as identity primary key,
    position text not null,
    name text not null,
    photo_url text,
    sort_order integer not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.meetings (
    id bigint generated by default as identity primary key,
    meeting_date date not null,
    title text not null,
    location text,
    chairperson text,
    agenda text,
    decisions text,
    minutes text,
    created_at timestamptz not null default now()
);

create table if not exists public.gallery_photos (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    album text not null default 'General',
    year integer,
    visibility text not null default 'public' check (visibility in ('public','member')),
    image_url text not null,
    created_at timestamptz not null default now()
);

alter table public.committee enable row level security;
alter table public.meetings enable row level security;
alter table public.gallery_photos enable row level security;

create index if not exists committee_active_sort_idx on public.committee(active, sort_order, id);
create index if not exists meetings_date_idx on public.meetings(meeting_date desc, id desc);
create index if not exists gallery_visibility_created_idx on public.gallery_photos(visibility, created_at desc);
create index if not exists gallery_album_year_idx on public.gallery_photos(album, year);

-- New site_settings keys are created automatically by the application.
